/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nishtha20
 */
import java.util.*;
import java.sql.*;
public class signup_page extends javax.swing.JFrame {

    
    public signup_page() {
        initComponents();
    }
    @SuppressWarnings("unchecked")
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("eg Ravi210201");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 190, -1));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 305, 187, -1));

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel2.setText("MOBILE NO.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 357, 187, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 378, 187, -1));

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel3.setText("PASSWORD ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 189, 187, -1));

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 210, -1));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel4.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 249, 187, -1));

        jPasswordField2.setText("jPasswordField2");
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 210, 210, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel5.setText("EMAIL ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 409, 187, -1));

        jTextField3.setText("eg noname@example.com");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 430, 187, -1));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel6.setText("FIRST NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 189, -1, -1));

        jTextField4.setText("eg Ravi");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 210, 187, -1));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel7.setText("LAST NAME");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 249, 190, -1));

        jTextField5.setText("eg Kishan");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 267, 187, -1));

        jLabel8.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel8.setText("CHOOSE SECURITY QUESTION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 305, 210, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select--security--question","Enter your birth place", "Enter your pet's name", "Enter your first vehicle registration number", "Enter your favourite class teacher's name" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 331, 270, -1));

        jLabel9.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel9.setText("ANSWER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 370, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 396, 200, 54));

        jLabel10.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel10.setText("SIGNUP");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 53, 150, 43));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 479, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aeroplane-Airbus-in-sky-HD-Wallpaper (4).jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 0, 1220, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try {
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                
            } catch (ClassNotFoundException ex) {
                
            }
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","prathma");
            Statement st = con.createStatement();
            String s = (String)jComboBox1.getSelectedItem();
            String sq = "INSERT INTO USER_TABLE VALUES ('"+jTextField1.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jPasswordField2.getText()+"','"+s+"','"+jTextArea1.getText()+"')";
            //System.out.println (jTextField1.getText() + jTextArea1.getText());
            String s1,s2;
            s1 = jTextField1.getText();
            //System.out.println(s1);
           if(s1.equals("eg RAVI210201") || jTextField4.getText().equals("eg Ravi") || jTextField5.getText().equals("eg Kishan") || jTextField2.getText().equals(null)||  jTextField3.getText().equals("eg noname@example.com") || jPasswordField2.getText().equals(null) || jPasswordField1.getText().equals(null) || jComboBox1.getActionCommand().equals("Select--security--question") || jTextArea1.getText().equals(null)) {
            //   System.out.println("yes"); 
               Allfieldsreqd afr = new Allfieldsreqd();
                afr.setVisible(true);
                   
            } else if(!jPasswordField1.getText().equals(jPasswordField2.getText())) {
                Allfieldsreqd af = new Allfieldsreqd();
                af.setVisible(true);
                   
            }
           else {
             ResultSet rs = st.executeQuery(sq);
             AccountCreated ac = new AccountCreated();
             ac.setVisible(true);
             this.setVisible(false);
           }
            
            
            
        } catch (SQLException se) {
            NewRequestexception nr = new NewRequestexception();
              nr.setVisible(true);
              this.setVisible(false);
        }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup_page().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
